# Generated by Django 3.2.12 on 2023-03-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercalories',
            old_name='fat',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='usercalories',
            old_name='protein',
            new_name='proteins',
        ),
        migrations.AddField(
            model_name='usercalories',
            name='username',
            field=models.CharField(default='~', max_length=200),
        ),
    ]
