# Generated by Django 3.2.12 on 2023-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0002_auto_20230301_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalories',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercalories',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercalories',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
    ]
