# Generated by Django 3.2.12 on 2023-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0005_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='user',
            field=models.CharField(default='~', max_length=200),
        ),
    ]
